# Generated by Django 3.2.8 on 2021-12-18 21:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_userscheckedtestitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersCheckedTestItems',
            new_name='UsersTestItems',
        ),
    ]
